Base:
  training_dataset: "flexthink/audiomnist"

Data:
  source_sr: 48000
  target_sr: 16000
  n_fft: 256
  hop_length: 128
  power: 2.0
  batch_size: 32
  num_workers: 0

Training:
  n_epoch: 10
  lr: 1e-4
